"""Cline SDK - update a surgeon's initial plan using the measured deformation.

The deterministic engine always works offline: every coordinate the doctor enters
(preoperative RAS mm) is mapped through the learned displacement field into the
intraoperative space, and a parameterized planning document is generated from the
measured shift.  If ``ANTHROPIC_API_KEY`` is exported, the narrative is additionally
rewritten in natural language by Claude (optional upgrade, never required).
"""
from __future__ import annotations

import os
from datetime import datetime

import numpy as np

from .preprocess import voxel_to_world, world_to_voxel
from .relocate import direction_phrase, invert_point

ANTHROPIC_URL = 'https://api.anthropic.com/v1/messages'
DEFAULT_MODEL = os.environ.get('CLINE_MODEL', 'claude-sonnet-4-5')


def transform_point(xyz, disp, moving_affine, fixed_affine) -> dict:
    """Map one preoperative point (RAS mm) into the post-shift intraoperative space."""
    pre = np.asarray(xyz, dtype=np.float64)
    vox_pre = world_to_voxel(moving_affine, pre)
    vox_fixed = invert_point(disp, vox_pre)
    updated = voxel_to_world(fixed_affine, vox_fixed)
    delta = updated - pre
    return {
        'preop_mm': pre.round(2).tolist(),
        'updated_mm': updated.round(2).tolist(),
        'delta_mm': delta.round(2).tolist(),
        'delta_magnitude_mm': float(np.linalg.norm(delta)),
        'direction': direction_phrase(delta),
    }


def _guidance(reloc: dict, updated_points: list) -> list:
    """Parameterized navigation guidance derived from the measured shift."""
    shift = reloc['shift_magnitude_mm']
    jac = reloc.get('jacobian', {})
    bullets = [
        f'Tumour centre moved {shift:.1f} mm {reloc["shift_direction"]} relative to the '
        'affine-aligned preoperative position (geometric resampling alone).',
        'Re-confirm the planned entry point and trajectory against the updated '
        'coordinates before incision; the preoperative skin map no longer reflects '
        'the intraoperative anatomy.',
    ]
    if shift >= 5.0:
        bullets.insert(0, 'LARGE SHIFT DETECTED (>5 mm): the initial plan is no longer '
                          'metrically valid - rely on the updated coordinates below.')
    elif shift >= 2.0:
        bullets.insert(0, 'Moderate brain shift (2-5 mm): update trajectory angles and '
                          'depth stops before drilling.')
    else:
        bullets.insert(0, 'Shift is small (<2 mm): initial plan remains approximately '
                          'valid; verify with intraoperative imaging as usual.')
    if jac.get('pct_nonpositive', 0) > 0.1:
        bullets.append(f'Warning: {jac["pct_nonpositive"]:.2f}% of the deformation field '
                       'has non-positive Jacobian (folding) - treat millimetre-level '
                       'coordinates near those regions with extra caution.')
    for pt in updated_points:
        if pt['delta_magnitude_mm'] >= 1.0:
            bullets.append(f'Point "{pt["label"]}" shifted {pt["delta_magnitude_mm"]:.1f} mm '
                           f'toward the {pt["direction"]}.')
    return bullets


def _deterministic_plan(plan: dict, updated_points: list, reloc: dict, case: str) -> str:
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    pre, aff, shf = reloc['preop']['mm'], reloc['affine_aligned']['mm'], reloc['shifted']['mm']
    lines = [
        f'SURGICAL PLAN UPDATE - case {case}',
        f'Generated by Cline SDK ({now}, deterministic engine)',
        '',
        '1. TUMOUR STATUS',
        f'   - Preoperative centre (preop MRI)  : {pre[0]:.1f}, {pre[1]:.1f}, {pre[2]:.1f} mm RAS',
        f'   - After affine alignment only       : {aff[0]:.1f}, {aff[1]:.1f}, {aff[2]:.1f} mm RAS',
        f'   - CURRENT location (after shift)   : {shf[0]:.1f}, {shf[1]:.1f}, {shf[2]:.1f} mm RAS',
        f'   - Net brain shift                  : {reloc["shift_magnitude_mm"]:.1f} mm '
        f'toward the {reloc["shift_direction"]}',
        '',
        '2. UPDATED NAVIGATION COORDINATES',
    ]
    for pt in updated_points:
        u = pt['updated_mm']
        p = pt['preop_mm']
        lines.append(f'   - {pt["label"]}: ({u[0]:.1f}, {u[1]:.1f}, {u[2]:.1f}) mm RAS '
                     f'[was ({p[0]:.1f}, {p[1]:.1f}, {p[2]:.1f}), '
                     f'moved {pt["delta_magnitude_mm"]:.1f} mm]')
    lines += ['', '3. GUIDANCE']
    lines += [f'   * {b}' for b in _guidance(reloc, updated_points)]
    if plan.get('notes', '').strip():
        lines += ['', '4. SURGEON NOTES (carried over from the initial plan)']
        lines += [f'   {ln}' for ln in plan['notes'].strip().splitlines()]
    lines += ['', '5. INITIAL PLAN STEPS (review against updated coordinates)']
    for i, step in enumerate(plan.get('steps', []), 1):
        if step.strip():
            lines.append(f'   {i}. {step.strip()}')
    lines += ['', 'SAFETY: this document is decision support only. All coordinates must',
              'be verified with intraoperative imaging and the surgical team.']
    return '\n'.join(lines)


def _claude(prompt: str, system: str) -> str | None:
    key = os.environ.get('ANTHROPIC_API_KEY')
    if not key:
        return None
    try:
        import requests

        resp = requests.post(
            ANTHROPIC_URL,
            headers={'x-api-key': key, 'anthropic-version': '2023-06-01',
                     'content-type': 'application/json'},
            json={'model': DEFAULT_MODEL, 'max_tokens': 2000,
                  'system': system, 'messages': [{'role': 'user', 'content': prompt}]},
            timeout=60,
        )
        resp.raise_for_status()
        return ''.join(b.get('text', '') for b in resp.json().get('content', []))
    except Exception:
        return None


def update_plan(plan: dict, disp, moving_affine, fixed_affine, reloc: dict,
                case: str = 'unknown') -> dict:
    """Update the doctor's plan. Returns transformed points + narrative + engine info."""
    updated_points = [
        {'label': p.get('label', f'Point {i + 1}'),
         **transform_point([p['x'], p['y'], p['z']], disp, moving_affine, fixed_affine)}
        for i, p in enumerate(plan.get('points', []))
        if all(k in p for k in ('x', 'y', 'z'))
    ]
    narrative = _deterministic_plan(plan, updated_points, reloc, case)
    engine = 'deterministic'

    system = ('You are Cline, a neurosurgical planning assistant embedded in NeuroVista. '
              'Rewrite the provided plan update for the operating surgeon: clear, precise, '
              'structured with markdown headers. Keep every number exactly as given. '
              'Append a short "Verification checklist" section.')
    llm = _claude(f'Measured shift metrics:\n{reloc}\n\nPlan draft to rewrite:\n{narrative}',
                  system)
    if llm:
        narrative, engine = llm, f'claude ({DEFAULT_MODEL})'

    return {'points': updated_points, 'plan_text': narrative, 'engine': engine,
            'generated_at': datetime.now().isoformat(timespec='seconds')}


def ask(question: str, reloc: dict, case: str) -> str:
    """Answer a doctor's question with case context (LLM if configured, else rules)."""
    system = ('You are Cline, a neurosurgical planning assistant embedded in NeuroVista. '
              'Answer concisely and clinically, using only the provided case metrics. '
              'Always remind that final decisions require intraoperative verification.')
    llm = _claude(f'Case {case} metrics:\n{reloc}\n\nQuestion: {question}', system)
    if llm:
        return llm

    q = question.lower()
    shift = reloc['shift_magnitude_mm']
    jac = reloc.get('jacobian', {})
    if 'jacob' in q or 'fold' in q or 'quality' in q:
        answer = (f'Deformation Jacobian: min {jac.get("min", float("nan")):.3f}, mean '
                  f'{jac.get("mean", float("nan")):.3f}, '
                  f'{jac.get("pct_nonpositive", 0):.2f}% non-positive (folding). '
                  + ('Acceptable for planning.' if jac.get('pct_nonpositive', 0) <= 0.1
                     else 'Inspect folded regions before trusting coordinates there.'))
    elif 'plan' in q or 'update' in q or 'navigat' in q:
        answer = ('Use "Update plan" to map every preoperative coordinate through the '
                  'displacement field into intraoperative space. The updated document '
                  'lists new coordinates, the net shift and a guidance section.')
    elif 'where' in q or 'tumour' in q or 'tumor' in q:
        s = reloc['shifted']['mm']
        answer = (f'The tumour centre is now at ({s[0]:.1f}, {s[1]:.1f}, {s[2]:.1f}) mm RAS '
                  f'in intraoperative space - {shift:.1f} mm from its affine-aligned '
                  'position.')
    elif 'shift' in q or 'how much' in q or 'moved' in q:
        answer = (f'Measured brain shift of the tumour centre is {shift:.1f} mm toward the '
                  f'{reloc["shift_direction"]}. Mean field magnitude '
                  f'{reloc["field_magnitude_mm"]["mean"]:.1f} mm, p95 '
                  f'{reloc["field_magnitude_mm"]["p95"]:.1f} mm.')
    else:
        answer = ('I can report on: tumour shift magnitude/direction, deformation quality '
                  '(Jacobian), updated coordinates, and the updated plan. '
                  '(Set ANTHROPIC_API_KEY for free-form AI answers.)')
    return answer + '\n\n(Deterministic engine - set ANTHROPIC_API_KEY to enable full AI mode.)'
